# Generated by Django 5.2.3 on 2025-08-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_hydjobs_address_alter_hydjobs_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bngjobs',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.CharField(max_length=225),
        ),
    ]
